In [1]:
import cv2
import imutils
import numpy as np
import pytesseract

In [2]:
# pytesseract.pytesseract.tesseract_cmd = r'C:/Tesseract-OCR/tesseract.exe'

In [3]:
pytesseract.pytesseract.tesseract_cmd = r'C:\Users\SecondaryEducation\Tesseract-OCR\tesseract'

In [4]:
img = cv2.imread("vkcar.jpg",cv2.IMREAD_COLOR)


In [5]:
print(img)

[[[229 230 214]
  [228 229 213]
  [228 229 213]
  ...
  [ 29  39  33]
  [ 29  39  33]
  [ 16  26  20]]

 [[229 230 214]
  [228 229 213]
  [228 229 213]
  ...
  [ 31  41  35]
  [ 33  43  37]
  [ 34  44  38]]

 [[227 230 214]
  [226 229 213]
  [226 229 213]
  ...
  [ 33  40  35]
  [ 26  33  28]
  [ 27  34  29]]

 ...

 [[187 230 245]
  [186 229 244]
  [185 228 243]
  ...
  [151 151 165]
  [117 117 131]
  [124 124 138]]

 [[186 229 244]
  [186 229 244]
  [185 228 243]
  ...
  [182 182 196]
  [163 163 177]
  [153 153 167]]

 [[182 225 240]
  [182 225 240]
  [181 224 239]
  ...
  [185 185 199]
  [189 189 203]
  [189 189 203]]]


In [6]:
cv2.imshow('11',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
# img = cv2.resize(img, (600,400) )

In [8]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) 
gray = cv2.bilateralFilter(gray, 11, 17, 17)

In [9]:
cv2.imshow('11',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
edged = cv2.Canny(gray, 30, 200) 


In [11]:
cv2.imshow('11',edged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
contours = cv2.findContours(edged.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
contours = imutils.grab_contours(contours)
contours = sorted(contours, key = cv2.contourArea, reverse = True)[:10]
screenCnt = None

In [13]:
cv2.imshow('11',edged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
for c in contours:
    approx = cv2.approxPolyDP(c, 10, True)
 
    if len(approx) == 4:
        screenCnt = approx
        break

In [15]:
screenCnt

array([[[283, 317]],

       [[282, 333]],

       [[184, 339]],

       [[185, 319]]], dtype=int32)

In [16]:
approx

array([[[283, 317]],

       [[282, 333]],

       [[184, 339]],

       [[185, 319]]], dtype=int32)

In [17]:
cv2.imshow('11',edged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
if screenCnt is None:
    detected = 0
    print ("No contour detected")
else:
     detected = 1

In [19]:
if detected == 1:
    cv2.drawContours(img, [screenCnt], -1, (0, 0, 255), 2)

In [20]:
mask = np.zeros(gray.shape,np.uint8)
new_image = cv2.drawContours(mask,[screenCnt],0,255,-1,)
new_image = cv2.bitwise_and(img,img,mask=mask)

In [21]:
cv2.imshow('11',new_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
(x, y) = np.where(mask == 255)
(topx, topy) = (np.min(x), np.min(y))
(bottomx, bottomy) = (np.max(x), np.max(y))
Cropped = gray[topx:bottomx+1, topy:bottomy+1]

In [23]:
cv2.imshow('11',Cropped)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
number = pytesseract.image_to_string(Cropped, config='--psm 11')
print("License Plate Recognition\n")
print("Detected license plate Number is:",number)
img = cv2.resize(img,(500,300))
Cropped = cv2.resize(Cropped,(400,200))
cv2.imshow('car',img)
cv2.imshow('Cropped',Cropped)
cv2.waitKey(0)
cv2.destroyAllWindows()

License Plate Recognition

Detected license plate Number is: HR 26 BW 0018 |

